[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
solc-optimizer = true
solc-optimizer-runs = 200
viaIR = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
]

[etherscan]
sepolia = { key = "CBTKPBT7ZHVZ3QEKT761YUTDAFYDUGEUTE", url = "https://api-sepolia.etherscan.io/api" }
flow = { key = "", url = "https://api-flow.etherscan.io/api" }
linea-sepolia = { key = "Q2RM1Z7Y7FS1BA1QPSRGMXRZ84EYU4FB4N", url = "https://api-sepolia.lineascan.build/api" }
